server:
  port: 10000
  servlet:
    session:
      tracking-modes: cookie
      timeout: 10m

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/threetier?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: spring
    password: 1234

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 5MB
      max-file-size: 5MB
      max-request-size: 15MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*.xml
  type-handlers-package: com.example.threetier.config.mybatis.handler
  type-aliases-package: com.example.threetier.domain;com.example.threetier.dto;

